export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as VideoBackground } from './video/VideoBackground'
export { default as ServicesSection } from './ServicesSection'
export { default as ScrollToTop } from './scrollToTop/ScrollToTop'
export { default as QualitySection } from './qualitySection/QualitySection'
export { default as Products } from './products/Products'
export { default as GallerySection } from './gallerySection/GallerySection'
export { default as GallerySection2 } from './gallerySection2/GallerySection2'
export { default as Testimonials } from './testimonials/Testimonials'
export { default as Footer } from './footer/Footer'

